apiVersion: apps/v1
kind: Deployment
metadata:
  name: membermicroservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MemberMicroservice
  template:
    metadata:
      labels:
        app: MemberMicroservice
    spec:
      containers:
      - name: memberrepos
        image: policycr.azurecr.io/memberrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: membermicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MemberMicroservice